In [1]:
import numpy as np

In [2]:
data = [6, 7.5, 8, 0, 1]

In [3]:
arr1 = np.array(data)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data2 = [[1,2,3,7], [5,3,2,4]]

In [10]:
arr2 = np.array(data2)

In [11]:
arr2

array([[1, 2, 3, 7],
       [5, 3, 2, 4]])

In [12]:
#Type array
arr2.dtype

dtype('int32')

In [13]:
# Generate zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.empty(2)

array([2.4190752e-312, 1.0609979e-312])

In [17]:
np.empty((2,2))

array([[6. , 7.5],
       [8. , 1. ]])

In [18]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
np.arang

TypeError: arange: scalar arguments expected instead of a tuple.