In [1]:
import numpy as np

In [2]:
data = [6, 7.5, 8, 0, 1]

In [3]:
arr1 = np.array(data)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data2 = [[1,2,3,7], [5,3,2,4]]

In [10]:
arr2 = np.array(data2)

In [11]:
arr2

array([[1, 2, 3, 7],
       [5, 3, 2, 4]])

In [12]:
#Type array
arr2.dtype

dtype('int32')

In [13]:
# Generate zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.empty(2)

array([2.4190752e-312, 1.0609979e-312])

In [17]:
np.empty((2,2))

array([[6. , 7.5],
       [8. , 1. ]])

In [18]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [2]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [4]:
arr1 = np.array([1,2,3], dtype=np.int32)

In [8]:
float64 = arr1.astype(np.float64)

In [9]:
float64.dtype

dtype('float64')

## Operation between Arrays and scalars

In [10]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [12]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [14]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

## Basic indexing and slicing

In [15]:
arr = np.arange(10)

In [16]:
arr[5]

5

In [17]:
arr[1:3]

array([1, 2])

In [19]:
arr[3:4] = 12

In [20]:
arr

array([ 0,  1,  2, 12,  4,  5,  6,  7,  8,  9])

In [21]:
arr[:] = 64

In [22]:
arr

array([64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [23]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [24]:
arr2d[0][0]

1

In [25]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [26]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr3d[0][0][1]

2

## universal function

In [30]:
arr = np.arange(10)

In [31]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [35]:
from numpy import random
x = random.randn(8)

In [37]:
y = random.randn(8)

In [38]:
x

array([-0.19857304, -0.01757631, -0.12647286,  0.12937248, -1.26545556,
        0.04632583, -1.26152726,  0.28186179])

In [39]:
y

array([-0.34140351, -1.42902178,  1.21808561,  1.00285143,  0.19934554,
       -0.48372744, -0.54006702,  0.92613048])

In [40]:
np.maximum(x,y)

array([-0.19857304, -0.01757631,  1.21808561,  1.00285143,  0.19934554,
        0.04632583, -0.54006702,  0.92613048])