In [1]:
import numpy as np
from numpy import random

In [2]:
arr = np.random.randn(5, 4)

In [3]:
arr.mean()

0.03083081638392825

In [4]:
np.mean(arr)

0.03083081638392825

In [5]:
arr.sum()

0.616616327678565

In [6]:
arr.mean(axis=1)

array([-0.20959461, -0.73613769,  0.61563805,  0.11850533,  0.36574301])

In [7]:
arr.sum(0)

array([-2.6643002 ,  1.34897741,  2.33686997, -0.40493085])

In [8]:
arr.cumsum(0)

array([[ 0.60174821, -0.03082991, -1.14455204, -0.26474468],
       [-0.07245385, -0.08466859, -2.35110968, -1.27469707],
       [-1.46955969,  1.30152246, -0.49736549, -0.65497429],
       [-0.75200086,  0.75962481,  0.8579564 , -1.71193606],
       [-2.6643002 ,  1.34897741,  2.33686997, -0.40493085]])