In [1]:
import numpy as np

In [4]:
ints = np.ones(10, dtype=np.uint16)
ints

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint16)

In [5]:
floats = np.ones(10, dtype=np.float32)
floats

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [6]:
np.issubdtype(ints.dtype, np.integer)

True

In [7]:
np.issubdtype(floats.dtype, np.floating)

True

In [8]:
## Al metaclass
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

### Reshaping Arrays

In [9]:
arr = np.arange(8)

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [14]:
# arr.reshape((2,5))# Mostrará un error porque el arr tiene tamaño 8 
# y el reshape 2* 5 = 10.

In [22]:
arr = np.arange(15)
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
arr.shape

(15,)

In [25]:
arr = np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
arr.ravel() # produce una copia de los datos para aplanarlo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
arr.ravel('F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

### Concatenating and spliting

In [29]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

In [30]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [32]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### Repeating Elements: tile and repeat

In [34]:
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [36]:
arr.repeat([2,4,1])

array([0, 0, 1, 1, 1, 1, 2])

In [37]:
from numpy.random import randn

In [38]:
arr = randn(2,2)

In [39]:
arr.repeat(2, axis=0)

array([[-1.70693783, -0.72041429],
       [-1.70693783, -0.72041429],
       [-0.23375719, -0.52776931],
       [-0.23375719, -0.52776931]])

In [40]:
np.tile(arr,2)

array([[-1.70693783, -0.72041429, -1.70693783, -0.72041429],
       [-0.23375719, -0.52776931, -0.23375719, -0.52776931]])

### Fancy indexing

In [41]:
arr = np.arange(10) * 100